# Toggle enable/disable laptop touchpad

bindsym $mod+Mod1+t exec swaymsg input type:touchpad events toggle enabled disabled && \
	(swaymsg -t get_inputs | jq -r '.[] | select(.type == "touchpad") | .libinput.send_events' | grep -q "enabled" && \
		notify-send "Touchpad" "Enabled" -i input-touchpad || \
		notify-send "Touchpad" "Disabled" -i input-touchpad-symbolic)
