# Status Bar: waybar
#
# Read `man 5 sway-bar` for more information about this section.
# Read `man 5 waybar` for more information about the waybar instance style and layout configuration
#
# Requires: waybar

bar {
    # Require: ~/.local/bin/waybar-sway with execute permission
    swaybar_command waybar-sway
}
